/*
 * generated by Xtext 2.31.0
 */
package soal.dsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import soal.dsl.parser.antlr.internal.InternalSoalDslParser;
import soal.dsl.services.SoalDslGrammarAccess;

public class SoalDslParser extends AbstractAntlrParser {

	@Inject
	private SoalDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSoalDslParser createParser(XtextTokenStream stream) {
		return new InternalSoalDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "SoalModel";
	}

	public SoalDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SoalDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
