/*
 * generated by Xtext 2.31.0
 */
package soal.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSoalDslScopeProvider extends DelegatingScopeProvider {
}
