/*
 * generated by Xtext 2.31.0
 */
package soal.dsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import soal.dsl.ui.internal.DslActivator;

public class SoalDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DslActivator.getInstance().getInjector("soal.dsl.SoalDsl");
	}

}
